### ISSUE TITLE
For Wordpress projects, WP_HOME and WP_SITEURL is not set

### ISSUE THREAD

**Issue by blocher** [EngageDC/dirt#6]
WP_HOME and WP_SITEURL are not set when creating a Wordpress Project, using Dirt apply, or deploying to stage unless and empty WP_HOME and WP_SITEURL are already present in wp-config-sample.php.  Dirt should add these to wp-config-sample

**Comment by MiniCodeMonkey** [comment]
@blocher This was fixed with your recent commit, right?
